language: python
python: "3.6"

branches:
  only:
    - master

env:
  # Github Pages
  - GH_REF: github.com/USTC-Resource/USTC-Course

install:
  - pip install --upgrade pip
  - pip install markdown pypinyin

script:
  - python utils/genReadme.py
  - python utils/genIndex.py

after_script:
  # Build Master Repository(Coding Pages) 
  - git config user.name "mbinary"
  - git config user.email "zhuheqin1@gmail.com"
  - cd docs
  - git init
  - git remote add origin git@github.com:USTC-Resource/USTC-Course.git
  - git add --all
  - git commit -m "Travis-CI Update pages with build $TRAVIS_BUILD_NUMBER"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

notifications:
  email:
    recipients:
      - zhuheqin1@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
